#+title: QPS Prototype design for CAPTAN+ w/ADS9813EVM

* Quick-start

Navigate to =fw= and source =runme.sh=. This will create the Vivado project directly under the =fw= directory.

* Info summary

| Main clock         | 150MHz |
| ADC Sampling clock | 4MHz   |
| Sampling Rate      | 1MSps  |

* Description

The design connects two principal subsystems: the ADS9813EVM evaluation board, and the GEL ethernet board. The SPI programming of the ADCs is currently handled via a Microblaze core via the provided code in =sw=. Later, this will be ported to HDL to save up on resources.

Incoming ADC data is in double data rate (DDR) but initial tests showed that the provided data clock was slightly out of sync with the actual data. Thus, this data clock passes through a PLL with programmable phase shift which ensures data is read cleanly. Currently, this phase shift is hard-coded to -15\deg and executed by the Microblaze, but soon the =adc_autoalign= module will handle this automatically.

The main clock is 150MHz sourced from the =USER_CLK1= clock generated by a Si570 chip. This powers the Microblaze and main DSP logic.
The Ethernet interface requires that the PHY's 125MHz RX_CLK be used for all its logic.

The complete flow is:

1. ADC is initialized by Microblaze
2. Data clock PLL's phase is programmed by Microblaze to a known-good value
2. Data stream is deserialized in FPGA
3. Deserialized data is sequenced and serialized as 24-bit words
4. Data is timestamped and fed to the GEL's "burst mode" input

Once running, otsdaq should be able to recognize the board with IP =192.168.133.7= and interface port =2007=. Using the =FEOtsUDPTemplateInterface= installed by =otsdaq-demo= with the =first_demo= dataset is sufficient to get a working data stream, but further customization is needed in otsdaq to interpret the data (WIP in <TBD> repository).
